/*
 Freebird. 
 Copyright © 2012 Starfish Web Consulting - starfishwebconsulting.co.uk
 Play more of our games at arcade.starfish.ie
 Source code: http://github.com/eoinmcg/freebird
 On the twitters: @eoinmcg
*/
(function(){var a=!1,b=/xyz/.test(function(){xyz})?/\b_super\b/:/.*/;this.Class=function(){};Class.extend=function(c){function d(){!a&&this.init&&this.init.apply(this,arguments)}var e=this.prototype;a=!0;var g=new this;a=!1;for(var f in c)g[f]="function"==typeof c[f]&&"function"==typeof e[f]&&b.test(c[f])?function(a,b){return function(){var c=this._super;this._super=e[a];var d=b.apply(this,arguments);this._super=c;return d}}(f,c[f]):c[f];d.prototype=g;d.prototype.constructor=d;d.extend=arguments.callee;
return d}})();"use strict";window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();
var SF={game:null,W:480,H:288,scale:1,entities:[],score:0,hiScore:localStorage.hiScore||1E3,newHiScore:!1,RATIO:null,currentWidth:null,currentHeight:null,canvas:null,ctx:null,ua:null,android:null,ios:null,lastTick:0,tick:0,time:0,fps:0,state:"loader",action:"Tap",fadeText:0,font:"Rammetto One, Verdana",debug:!1,pause:!1,screenshot:!1,tapped:!1,m:{x:null,y:null},offset:{top:0,left:0},hasAudio:!1,mute:!1,sfx:{},plays:0,lang:"en",phrases:null,init:function(){SF.RATIO=SF.W/SF.H;SF.currentWidth=SF.W;SF.currentHeight=
SF.H;SF.canvas=document.getElementsByTagName("canvas")[0];SF.canvas.width=SF.W;SF.canvas.height=SF.H;SF.ctx=SF.canvas.getContext("2d");SF.ua=navigator.userAgent.toLowerCase();SF.android=-1<SF.ua.indexOf("android")?!0:!1;SF.ios=-1<SF.ua.indexOf("iphone")||-1<SF.ua.indexOf("ipad")?!0:!1;SF.ipad=-1<SF.ua.indexOf("ipad")?!0:!1;SF.iphone=-1<SF.ua.indexOf("iphone")?!0:!1;SF.hasAudio=SF.ios||SF.android?!1:!0;SF.action=SF.android||SF.ios?"Tap":"Click";SF.Input.init();SF.lang=SF.getQueryString().lang||"en";
SF.phrases=SF.data.phrases[SF.lang];document.getElementById("o").innerHTML="<p>"+SF.tr("rotate_device")+"</p>";SF.resize();SF.changeState(SF.state);SF.loop();SF.reset();window.addEventListener("resize",SF.resize,!1);window.addEventListener("orientationchange",function(){window.scrollTo(0,1);SF.resize()},!1)},resize:function(){var a=document.getElementById("o"),b=document.getElementById("ad"),c=document.getElementById("adLarge");SF.currentW=window.innerWidth/SF.W;SF.currentH=window.innerHeight/SF.H;
480>=window.innerWidth&&(SF.canvas.style.width="480px",SF.canvas.style.height="288px",SF.scale=1);960==window.innerWidth&&(SF.canvas.style.width="960px",SF.canvas.style.height="576px",SF.scale=2);1024<=window.innerWidth&&(SF.canvas.style.width="1024px",SF.canvas.style.height="614px",SF.scale=2.233333);SF.android&&(document.body.style.height=window.innerHeight+50+"px",document.body.height=window.innerHeight+50+"px");SF.offset.top=SF.canvas.offsetTop;SF.offset.left=SF.canvas.offsetLeft;b.style.left=
Math.floor((window.innerWidth-320)/2)+"px";b.style.top=parseInt(SF.canvas.style.height,10)-70+"px";c.style.left=Math.floor((window.innerWidth-300)/2)+"px";c.style.top=parseInt(SF.canvas.style.height,10)-350+"px";480>window.innerWidth?(a.style.display="block",SF.canvas.style.display="none",b.style.display="none"):(a.style.display="none",SF.canvas.style.display="block");window.setTimeout(function(){window.scrollTo(0,1)},1)},loop:function(){requestAnimFrame(SF.loop);SF.game.update();SF.game.render();
SF.tapped=!1;SF.tick+=1;SF.time=0.02*(new Date).getTime();SF.fadeText=Math.sin(0.2*SF.time)+1;SF.fps=~~(1E3/((new Date).getTime()-SF.lastTick));SF.lastTick=(new Date).getTime()},changeState:function(a){SF.reset();SF.game=new window["SF_"+a]({})},reset:function(){SF.entities=[];SF.level=0;SF.pause=!1;SF.tapped=!1;SF._t=0},tr:function(a){return"undefined"===typeof SF.phrases[a]?a:SF.phrases[a]},getQueryString:function(){for(var a={},b=location.search.substring(1),c=/([^&=]+)=([^&]*)/g,d;d=c.exec(b);)a[decodeURIComponent(d[1])]=
decodeURIComponent(d[2]);return a},Draw:{clear:function(){SF.ctx.clearRect(0,0,SF.W,SF.H)},rect:function(a,b,c,d,e){SF.ctx.fillStyle=e;SF.ctx.fillRect(a,b,c,d)},roundRect:function(a,b,c,d,e,g,f){f&&(SF.ctx.strokeStyle=f,SF.ctx.lineWidth=3);SF.ctx.fillStyle=g;SF.ctx.beginPath();SF.ctx.moveTo(a+e,b);SF.ctx.arcTo(a+c,b,a+c,b+d,e);SF.ctx.arcTo(a+c,b+d,a,b+d,e);SF.ctx.arcTo(a,b+d,a,b,e);SF.ctx.arcTo(a,b,a+c,b,e);SF.ctx.closePath();f&&SF.ctx.stroke();SF.ctx.fill()},circle:function(a,b,c,d,e){e&&(SF.ctx.strokeStyle=
e,SF.ctx.lineWidth=3);SF.ctx.fillStyle=d;SF.ctx.beginPath();SF.ctx.arc(a+5,b+5,c,0,2*Math.PI,!0);SF.ctx.closePath();e&&SF.ctx.stroke();SF.ctx.fill()},image:function(a,b,c){SF.ctx.drawImage(a,b,c)},star:function(a,b,c){var d=0,e=3*(Math.PI/2),g=a,f=b,h=Math.PI/5;SF.ctx.save();SF.ctx.beginPath();SF.ctx.moveTo(a,b-5);for(d=0;5>d;d++)g=a+5*Math.cos(e),f=b+5*Math.sin(e),SF.ctx.lineTo(g,f),e+=h,g=a+8*Math.cos(e),f=b+8*Math.sin(e),SF.ctx.lineTo(g,f),e+=h;SF.ctx.lineTo(a,b-5);SF.ctx.fillStyle=c;SF.ctx.fill();
SF.ctx.closePath();SF.ctx.restore()},triangle:function(a,b,c){SF.ctx.save();SF.ctx.fillStyle="#fff";SF.ctx.beginPath();SF.ctx.lineTo(a,b);SF.ctx.lineTo(a,b+c);SF.ctx.lineTo(a+c,b+c/2);SF.ctx.fill();SF.ctx.closePath();SF.ctx.restore()},text:function(a,b,c,d,e,g){SF.ctx.font="bold "+d+"px "+SF.font;b=b||SF.W/2-SF.ctx.measureText(a).width/2;g&&(SF.ctx.fillStyle=g,SF.ctx.fillText(a,b-2,c+2));SF.ctx.fillStyle=e;SF.ctx.fillText(a,b,c)}},Input:{init:function(){var a=document.getElementsByTagName("canvas")[0];
window.addEventListener("keyup",function(a){if(32===a.keyCode)return SF.tapped=!0,a.preventDefault(),!1;192===a.keyCode&&(SF.screenshot=!SF.screenshot)},!1);a.addEventListener("click",function(a){SF.tapped=!0;SF.m.x=(a.pageX-SF.offset.left)/SF.scale;SF.m.y=(a.pageY-SF.offset.top)/SF.scale;a.preventDefault();return!1},!1);a.addEventListener("touchstart",function(a){SF.tapped=!0;var c=a.touches[0];SF.m.x=(c.pageX-SF.offset.left)/SF.scale;SF.m.y=(c.pageY-SF.offset.top)/SF.scale;a.preventDefault();return!1},
!1);a.addEventListener("touchmove",function(a){a.preventDefault();return!1},!1);a.addEventListener("touchend",function(a){a.preventDefault();return!1},!1)}}};
SF.Game=Class.extend({init:function(){SF.preventDefault=!1},update:function(){for(var a=SF.entities.length;a--;)SF.entities[a].update(),SF.entities[a].checkCollision&&SF.entities[a].collides(SF.entities[0])&&(SF.entities[a].hit(),SF.entities[0].hit(SF.entities[a].strength,SF.entities[a].name)),SF.entities[a].remove&&SF.entities.splice(a,1)},render:function(){for(i=0;i<SF.entities.length;i+=1)SF.entities[i].render()}});
SF.Anim=function(a){a=a||{};this.xOff=a.xOff||0;this.yOff=a.yOff||0;this.frames=a.frames||0;this.currentFrame=a.currentFrame||0;this.nextAnim=a.nextAnim||!1;this.frameSpeed=a.frameSpeed||3};
SF.Particle=function(a,b,c,d,e){this.x=a;this.y=b;this.r=c;this.col=d;this.type=e||"circle";this.name="particle";this.dir=1<2*Math.random()?1:-1;this.vx=~~(4*Math.random())*this.dir;this.vy=~~(7*Math.random());this.remove=!1;this.update=function(){this.x+=this.vx;this.y-=this.vy;this.vx*=0.99;this.vy*=0.99;this.vy-=0.35;this.y>SF.H&&(this.remove=!0)};this.render=function(){"star"===this.type?SF.Draw.star(this.x,this.y,this.col):SF.Draw.circle(this.x,this.y,this.r,this.col)}};SF.audio=document.querySelector("audio");
SF.audiosprite={coin:[0,0.3],bonus:[1,1.3],hurt:[2,2.4],die:[3,3.4],powerup:[4,4.7],tweet:[5,5.8]};SF.audioEnd=0;SF.audio.addEventListener("timeupdate",function(){SF.audio.currentTime>SF.audioEnd&&SF.audio.pause()},!1);SF.sfx=function(a){SF.hasAudio&&(!SF.mute&&SF.audiosprite[a])&&(SF.audio.currentTime=SF.audiosprite[a][0],SF.audioEnd=SF.audiosprite[a][1],SF.audio.play())};
SF.Sprite=Class.extend({init:function(a){this.x=a.x;this.y=a.y;this.w=a.w;this.h=a.h;this.vx=a.vx;this.vy=a.vy;this.xOff=a.xOff||0;this.yOff=a.yOff||0;this.anims=[];this.checkCollision=this.removeOnPause=this.killOnRespawn=this.remove=!1;this.strength=-1;this.r=this.w/2;this.q=this.r/2},update:function(){this.x+=this.vx;this.y+=this.vy;this.vx*=0.99;this.vy&&(this.vy*=0.99,this.vy+=0.04)},render:function(){if(this.img.src){this.animate();try{SF.ctx.drawImage(this.img,this.xOff,this.yOff,this.w,this.h,
~~this.x,~~this.y,this.w,this.h)}catch(a){console.log(a)}}else SF.Draw.rect(this.x,this.y,this.w,this.h,this.col)},animate:function(){SF.pause||(0===SF.tick%this.anims[this.anim].frameSpeed&&(this.anims[this.anim].currentFrame+=1),this.anims[this.anim].currentFrame>this.anims[this.anim].frames&&(this.anims[this.anim].currentFrame=0,this.anims[this.anim].nextAnim&&this.changeAnim(this.anims[this.anim].nextAnim)),this.xOff=this.anims[this.anim].xOff+this.anims[this.anim].currentFrame*this.w)},changeAnim:function(a){this.anim=
a;this.anims[this.anim].currentFrame=0},collides:function(a){this.left=this.x;this.right=this.x+this.w;this.top=this.y;this.bottom=this.y+this.h;a.left=a.x;a.right=a.x+a.w;a.top=a.y;a.bottom=a.y+a.h;return this.bottom<a.top||this.top>a.bottom||this.right<a.left||this.left>a.right?!1:!0},respawn:function(){this.killOnRespawn&&(this.remove=!0)},hit:function(){}});
SF.Button=SF.Sprite.extend({init:function(a){this._super(a);this.type="button";this.text=a.text||"";this.bgcol=a.bgcol||!1;this.col=a.col;this.shadow=a.shadow||!1;this.fade=a.fade||!1;this.size=a.size||14;this.x||(this.x=SF.W/2-this.w/2);SF.ctx.font="bold "+this.size+"px "+SF.font;this.textX=this.w/2-SF.ctx.measureText(this.text).width/2+this.x;this.textY=this.y+this.h/2},update:function(){var a={};this.textCol=this.fade?"rgba("+this.col+","+SF.fadeText+")":this.col;SF.tapped&&(a.x=SF.m.x,a.y=SF.m.y,
a.w=1,a.h=1,this.collides(a)&&this.clicked())},clicked:function(){console.log("CLicked: "+this.text)},render:function(){this.bgcol&&SF.Draw.rect(this.x,this.y,this.w,this.h,this.bgcol);this.text&&SF.Draw.text(this.text,this.textX,this.textY,this.size,this.textCol,this.shadow)}});SF.levels=[];SF.levels[1]={bg:{grad:"day",type:"hills",col:"#002000"},entities:{Coin:1,Tree:3}};SF.levels[2]={bg:{grad:"day",type:"hills",col:"#003000"},entities:{Coin:1,Tree:3,Fly:2}};
SF.levels[3]={bg:{grad:"day",type:"hills",col:"#004000"},entities:{Coin:1,Tree:2,Fly:2,Hornet:2,Powerup:1}};SF.levels[4]={bg:{grad:"dusk",type:"hills",col:"#001000"},entities:{Coin:2,Tree:2,Hornet:2,Mozzie:1}};SF.levels[5]={bg:{grad:"dusk",type:"hills",col:"#001000"},entities:{Coin:2,Hornet:2,Tree:2,Mozzie:1,Powerup:1}};SF.levels[6]={bg:{grad:"night",type:"stars",col:"#fff"},entities:{Coin:2,Tree:2,Hornet:2,Snapper:2}};
SF.levels[7]={bg:{grad:"night",type:"stars",col:"#fff"},entities:{Coin:2,Tree:2,Mozzie:2,Vamp:1,Powerup:1}};SF.levels[8]={bg:{grad:"dawn",type:"city",col:"#222"},entities:{Coin:2,Snapper:1,Vamp:1,Mozzie:1}};SF.levels[9]={bg:{grad:"day",type:"city",col:"#444"},entities:{Coin:2,Tree:2,Hornet:4,Powerup:1}};SF.levels[10]={bg:{grad:"day",type:"city",col:"#444"},entities:{Coin:2,Tree:1,Vamp:1,Mozzie:1,Hornet:2}};SF.levels[11]={bg:{grad:"dusk",type:"city",col:"#444"},entities:{Coin:2,Hornet:4,Vamp:2}};
SF.levels[12]={bg:{grad:"night",type:"stars",col:"#fff"},entities:{Coin:3,Tree:4,Hornet:4,Snapper:2}};SF.levels[13]={bg:{grad:"dawn",type:"rainbow",col:"#444"},entities:{Coin:3,Tree:1,Fly:1,Hornet:1,Mozzie:1,Snapper:1,Vamp:1,Powerup:1}};
SF.Bg={hills:function(a){SF.Draw.circle(0,SF.H+30,100,a);SF.Draw.circle(160,SF.H+30,120,a);SF.Draw.circle(300,SF.H+30,90,a);SF.Draw.circle(420,SF.H+30,140,a)},hills2:function(){},stars:function(){SF.Draw.circle(100,100,1,"#fff");SF.Draw.circle(150,30,1,"#fff");SF.Draw.circle(220,60,1,"#fff");SF.Draw.circle(300,50,1,"#fff");SF.Draw.circle(430,70,30,"#fff");SF.Draw.circle(415,70,30,"#012")},city:function(a){SF.Draw.rect(0,SF.H-30,SF.W,100,a);SF.Draw.rect(30,SF.H-100,30,100,a);SF.Draw.rect(70,SF.H-140,
50,140,a);SF.Draw.rect(90,SF.H-50,90,140,a);SF.Draw.rect(160,SF.H-140,40,140,a);SF.Draw.rect(160,SF.H-80,100,100,a);SF.Draw.rect(220,SF.H-130,20,140,a);SF.Draw.rect(300,SF.H-170,40,140,a);SF.Draw.rect(350,SF.H-120,60,100,a);SF.Draw.rect(410,SF.H-140,40,140,a)}};SF.data={title:"Freebird",desc:"Fly the birdie to freedom",ads:!0,tweetScore:!1,imgs:["b2.png","t.png","wing.png","gui.png"],sfx:[]};SF.speed=0;
SF.loadCallback=function(){var a;SF.gradients={};a=SF.ctx.createLinearGradient(0,0,0,SF.H);a.addColorStop(0,"#036");a.addColorStop(0.5,"#69a");a.addColorStop(1,"yellow");SF.gradients.dawn=a;a=SF.ctx.createLinearGradient(0,0,0,SF.H);a.addColorStop(0,"#69a");a.addColorStop(0.5,"#9cd");a.addColorStop(1,"#fff");SF.gradients.day=a;a=SF.ctx.createLinearGradient(0,0,0,SF.H);a.addColorStop(0,"#036");a.addColorStop(0.3,"#69a");a.addColorStop(1,"pink");SF.gradients.dusk=a;a=SF.ctx.createLinearGradient(0,0,
0,SF.H);a.addColorStop(0,"#036");a.addColorStop(1,"black");SF.gradients.night=a};
SF_loader=SF.Game.extend({init:function(a){this._super(a);this.loaded=!1;this.dir="a/";this.sfxType=SF.ios?".aif":".ogg";this.totalImgs=SF.data.imgs.length;this.totalSfx=SF.data.sfx.length;this.totalAssets=this.totalImgs+this.totalSfx;for(a=this.loadedSfx=this.loadedImgs=0;a<this.totalImgs;a++)this.loadImg(SF.data.imgs[a]);for(a=0;a<this.totalSfx;a++)this.loadSfx(SF.data.sfx[a]);document.getElementById("ad").style.display="none"},update:function(){this.loaded===this.totalAssets&&(SF.loadCallback(),
SF.changeState("splash"))},render:function(){var a=this.percentLoaded()/100*SF.W;SF.Draw.clear();SF.Draw.rect(0,0,SF.W,SF.H,"#000");SF.Draw.rect(0,SF.H/2,a,20,"green");SF.Draw.text(SF.tr("loading"),!1,250,30,"#fff","#000");SF.Draw.text(this.loaded+" / "+this.totalAssets,!1,270,10,"#555","#000")},loadImg:function(a){a=this.dir+a;var b=new Image,c=this;b.src=a;b.addEventListener("load",function(){c.loaded+=1},!1);b.addEventListener("error",function(){},!1)},loadSfx:function(a){var b=a;a=this.dir+a+
this.sfxType;var c="SF_"+a;if(SF.hasAudio){document.createElement("audio");SF.sfx[b]=document.createElement("audio");SF.sfx[b].src=a;SF.sfx[b].setAttribute("id",c);SF.sfx[b].load();SF.sfx[b].volume=0;SF.sfx[b].play();SF.sfx[b].autobuffer="true";SF.sfx[b].preload="auto";document.body.appendChild(SF.sfx[b]);var d=this;SF.sfx[b].addEventListener("canplaythrough",function(){d.loaded+=1;this.removeEventListener("canplaythrough",arguments.callee,!1);this.pause();this.currentTime=0.01},!1);SF.sfx[b].addEventListener("error",
function(){alert("error loading: "+a);d.loaded+=1},!1)}else this.loaded+=1},percentLoaded:function(){return~~(100*(this.loaded/(this.totalImgs+this.totalSfx)))}});
SF_intro=SF.Game.extend({init:function(a){this._super(a);document.getElementById("ad").style.display="none"},update:function(){},render:function(){SF._t=SF._t||1;SF._d=SF._d||-1;SF._r=SF._r||0.01;SF._t+=SF._r*SF._d;0.01>=SF._t&&(SF._d*=-1,SF._r=0.01);SF.Draw.rect(0,0,SF.W,SF.H,"#333");SF.Draw.text("Starfish Arcade",!1,100,34,"green");SF.Draw.text("presents...",!1,150,24,"green");SF.Draw.rect(0,0,SF.W,SF.H,"rgba(0,0,0,"+SF._t+")");if(1<=SF._t||SF.tapped)SF.Draw.clear(),SF.changeState("splash")}});
SF.intro=function(){};
SF_splash=SF.Game.extend({init:function(a){this._super(a);this.level=SF.levels[1];this.num_clouds=4;for(a=0;a<this.num_clouds;a+=1)SF.entities.push(new SF.Cloud({}));SF.ctx.font="bold 48px "+SF.font;this.logoWidth=SF.ctx.measureText("Freebird").width;this.wing=new Image;this.wing.src="a/wing.png";this.animOffset=this.animTimer=0},update:function(){SF._t-=0.02;SF.screenshot||(this._super(),SF.tapped&&(SF.score=0,SF.changeState("play"),SF.tapped=!1),this.animTimer+=1,0===this.animTimer%5&&(this.animOffset+=
25),20<this.animTimer&&(this.animTimer=0),75<this.animOffset&&(this.animOffset=0))},render:function(){if(!SF.screenshot){var a=0.02*(new Date).getTime(),a=8*Math.cos(0.09*a)+100,b=(SF.action+"_to_start").toLowerCase();SF.Draw.clear();SF.Draw.rect(0,0,SF.W,SF.H,SF.gradients.day);this._super();console.log("ok");SF.ctx.drawImage(this.wing,this.animOffset,0,25,25,SF.W/2-this.logoWidth/2-20,a-30,25,25);SF.ctx.drawImage(this.wing,this.animOffset,25,25,25,SF.W/2+this.logoWidth/2-5,a-30,25,25);SF.Draw.text(SF.tr("freebird"),
!1,a,48,"#edd400","#000");SF.Draw.text(SF.tr(b),!1,140,14,"rgba(255,0,255,"+SF.fadeText+")");SF.Draw.text(SF.tr("hiscore")+":  "+SF.hiScore,!1,30,14,"rgba(0,0,0,1)")}}});
SF_tutorial=SF.Game.extend({init:function(a){this._super(a);this.level=SF.levels[1];this.bird=new Image;this.bird.src="a/b2.png";this.coin=new SF.Coin({});this.coin.x=200;this.coin.y=SF.H-140;this.baddie=new SF.Fly({});this.baddie.x=300;this.baddie.y=SF.H-140;document.getElementById("ad").style.display="none"},update:function(){SF._t-=0.02;if(SF.tapped||-8>SF._t||2<=SF.plays)SF.changeState("play"),SF.tapped=!1;this._super()},render:function(){SF.Draw.clear();SF.Draw.rect(0,0,SF.W,SF.H,SF.gradients.day);
SF.Bg.hills("#001000");-0.5>SF._t?this.step_1.apply(this):SF.ctx.drawImage(this.bird,128,0,32,32,130,SF.H-32,32,32);-2>SF._t&&this.step_2.apply(this);-4>SF._t&&this.step_3.apply(this);-6>SF._t&&this.step_4.apply(this);SF.Draw.text("How To Play",!1,40,22,"#f0f");SF.Draw.text("SKIP >",410,SF.H-20,12,"rgba(255,255,255,1)");this._super()},step_1:function(){SF.Draw.text("1. "+SF.action+" screen to Fly",!1,70,18,"#000","rgba(255,255,255,0.4)");try{SF.ctx.drawImage(this.bird,0,0,32,32,130,SF.H-128,32,32)}catch(a){}},
step_2:function(){SF.Draw.text("2. Eat to keep your strength up",!1,100,18,"#000","rgba(255,255,255,0.4)");this.coin.render()},step_3:function(){SF.Draw.text("3. Avoid the baddies",!1,130,18,"#000","rgba(255,255,255,0.4)");this.baddie.render()},step_4:function(){SF.Draw.text("4. Fly 13km to freedom!",!1,160,18,"#000","rgba(255,255,255,0.4)");this.baddie.render()}});
SF_play=SF.Game.extend({init:function(a){this._super(a);SF.entities=[];SF.entities.push(new SF.Bird({}));SF.entities.push(new SF.Button_pause({w:50,h:30,x:SF.W-60,y:20,text:"",size:30}));SF.p1=SF.entities[0];SF.p1.health=100;SF.speed=0;SF.levelTimer=0;SF.plays+=1;document.getElementById("ad").style.display="none";document.getElementById("adLarge").style.display="none";SF.preventDefault=!1;SF.coins={};2>SF.plays&&SF.entities.push(new SF.Text({str:SF.tr((SF.action+"_to_fly").toLowerCase()),col:"#fff",
max:16,size:16,fade:0.001}))},update:function(){window.scrollTo(0,1);var a=0===SF.levelTimer%1024?!0:!1,b;if(!SF.screenshot)if(!0===SF.pause)for(a=0;a<SF.entities.length;a+=1)"gui"===SF.entities[a].type&&SF.entities[a].update();else{this._super();SF.score+=1;SF.levelTimer+=2;100<SF.p1.health&&(SF.p1.health=100);if(SF.score>SF.hiScore&&!1===SF.newHiScore){SF.newHiScore=!0;SF.sfx("tweet");for(b=0;30>b;b+=1)SF.entities.push(new SF.Particle(SF.W/2,SF.H/2-100,10,"rgba(255,0,255,1)","star"));SF.entities.push(new SF.Text({str:"New Hi Score",
col:"#f0f",max:30,size:30,fade:0.007}))}13312<SF.levelTimer&&SF.changeState("victory");a&&(SF.level+=1,this.levelUp());SF.p1.dead&&(SF.sfx("die"),SF.changeState("gameOver"))}},render:function(){var a=100<SF.p1.health?100:SF.p1.health,b=SF.levels[SF.level]||SF.levels[1],c=b.bg.grad||"day",d=b.bg.col,b=b.bg.type;SF.Draw.clear();SF.Draw.rect(0,0,SF.W,SF.H,SF.gradients[c]);SF.Bg[b](d);this._super();SF.Draw.rect(19,49,102,18,"#000");SF.Draw.rect(20,50,a,16,"#c20");SF.Draw.rect(20,58,a,8,"rgba(255,255,255,0.2)");
SF.Draw.text(~~SF.score,20,30,14,"#fff");SF.debug&&(SF.Draw.text("FPS "+SF.fps,350,15,12,"#fff"),SF.Draw.text("Entities "+SF.entities.length,350,30,12,"#fff"));!0===SF.pause&&SF.Draw.text("PAUSED",!1,110,40,"rgba(255,255,255,1)","rgba(0,0,0,1)")},levelUp:function(){var a,b,c;c=SF.levels[SF.level];"undefined"===typeof c&&(c=SF.levData[1]);for(b=0;b<SF.entities.length;b+=1)"function"===typeof SF.entities[b].respawn&&(SF.entities[b].killOnRespawn=!0);for(a in c.entities)if(c.entities.hasOwnProperty(a))for(b=
0;b<c.entities[a];b+=1)try{SF.entities.push(new SF[a]({}))}catch(d){}}});
SF_gameOver=SF.Game.extend({init:function(a){this._super(a);this.button={x:100,y:180,w:SF.W-200,h:50,col:"#00aced",text:{str:"Tweet Score",x:!1,y:210,size:18,col:"#000"},pressed:function(a,c){return a>this.x&&a<this.x+this.w&&c>this.y&&c<this.y+this.h}};this.tweet=new Image;this.tweet.src="a/t.png"},update:function(){this._super();console.log(SF.tapped);SF.tapped&&SF.changeState("splash")},render:function(){SF.Draw.rect(0,0,SF.W,SF.H,"rgba(255,0,0,0.01)");SF.Draw.rect(0,50,SF.W,70,"#900");SF.Draw.text("Game Over",
!1,100,44,"rgba(255,255,255,"+SF.fadeText+")");SF.newHiScore&&(SF.hiScore=SF.score,localStorage.hiScore=SF.hiScore,SF.Draw.rect(0,120,SF.W,50,"#600"),SF.Draw.text("New HiScore!",!1,150,20,"#fff"));SF.data.tweetScore&&this.tweetScore();SF._t+=1},tweetScore:function(){var a=this.button;if(SF.tapped&&60<SF._t){if(!0===a.pressed(SF.m.x,SF.m.y)){window.location="https://twitter.com/intent/tweet?&text=I+scored+"+SF.score+"+in+Freebird+-+http://arcade.starfish.ie/freebird";return}SF.score=0;SF.newHiScore=
!1;SF.changeState("splash")}SF.Draw.roundRect(a.x,a.y,a.w,a.h,3,a.col,"#fff");SF.Draw.text(a.text.str,!1,a.text.y,a.text.size,a.text.col);SF.ctx.drawImage(this.tweet,a.x+10,a.y+8)}});
SF_victory=SF.Game.extend({init:function(a){this._super(a);this.fireworks="tomato lightblue yellow orange lightgreen greenyellow plum white".split(" ");this.timer=0;this.setTimer();this.bird=new Image;this.bird.src="b.png"},update:function(){SF.tapped&&60<SF._t&&(SF.hiScore=SF.score,localStorage.hiScore=SF.hiScore,SF.score=0,SF.newHiScore=!1,SF.changeState("splash"));this.timer-=1;this._super();0>=this.timer&&this.setTimer()},render:function(){SF.Draw.rect(0,0,SF.W,SF.H,"#333");SF.Draw.text("Victory",
!1,100,44,"rgba(255,0,255,"+SF.fadeText+")");SF.Draw.text("You Win!",!1,150,30,"#f0f");this._super();try{SF.ctx.drawImage(this.bird,128,0,32,32,100,SF.H-32,32,32)}catch(a){}},setTimer:function(){var a=~~(Math.random()*this.fireworks.length);this.timer=5*Math.random();SF.entities.push(new SF.Particle(SF.W/2,-10,3,this.fireworks[a],"star"))}});
SF.Text=SF.Sprite.extend({init:function(a){this._super(a);this.name="text";this.max=a.max||30;this.size=a.size||5;this.col=a.col||"#000";this.speed=a.speed||0.5;this.fade=a.fade||0.02;this.opacity=1;this.str=a.str;this.x=a.x||-SF.W;this.y=a.y||SF.H/2;this.centerX=SF.W/2;this.shadow=a.shadow||!1;this.collides=!1},update:function(){this.size>=this.max?(this.size=this.max,this.opacity-=this.fade,this.y-=0.5):this.size+=this.speed;0>this.opacity&&(this.remove=!0);SF.ctx.font="bold "+this.size+"px "+SF.font;
this.x=this.centerX-SF.ctx.measureText(this.str).width/2},render:function(){SF.ctx.globalAlpha=this.opacity;this.shadow&&SF.Draw.text(this.str,this.x+2,this.y+2,this.size,this.shadow);SF.Draw.text(this.str,this.x,this.y,this.size,this.col);SF.ctx.globalAlpha=1}});
SF.Bird=SF.Sprite.extend({init:function(a){this._super(a);this.img=new Image;this.img.src="a/b2.png";this.col=a.col||"c4a000";this.x=150;this.y=SF.H-40;this.h=this.w=32;this.vx=0;this.vy=-1;this.anims.flap=new SF.Anim({xOff:0,yOff:0,frames:2,frameSpeed:3,nextAnim:"glide"});this.anims.glide=new SF.Anim({xOff:0,yOff:0,frames:0,frameSpeed:3});this.anims.run=new SF.Anim({xOff:96,yOff:0,frames:1,frameSpeed:7});this.anims.stand=new SF.Anim({xOff:128,yOff:0,frames:0});this.anims.hurt=new SF.Anim({xOff:192,
yOff:0,frames:0,nextAnim:"glide"});this.anims.dead=new SF.Anim({xOff:160,yOff:0,frames:0});this.anim="glide";this.name="bird";this.health=100;this.r=this.w/2;this.invincible=!1;this.hitDelay=this.counter=0},update:function(){this.hitDelay-=1;SF.tapped&&0<this.health&&(this.vy+=-1.7,this.changeAnim("flap"));this._super();0>=this.health?(this.health=0,this.changeAnim("dead")):0<this.hitDelay?this.changeAnim("hurt"):this.y>=SF.H-this.h?(this.y=SF.H-this.h,this.vy=0,this.changeAnim("run")):0>=this.y&&
0<this.health&&(this.y=0,this.vy=-1*(this.vy/2));0<this.counter&&(this.counter-=0.3);0>=this.counter&&(this.invincible=!1);0>=this.health&&this.y>=SF.H-this.h&&(this.dead=!0)},render:function(){var a;this._super();this.invincible&&(a=this.counter/100,SF.Draw.circle(this.x+this.r+2,this.y+this.r,this.w/2,"rgba(255,0,255,0.3)","rgba(85,0,85, "+a+")"))},hit:function(a,b){0>a&&0>this.hitDelay?!1===this.invincible&&0<this.health&&(0>this.hitDelay&&SF.sfx("hurt"),this.health+=a,this.hitDelay=20,this.changeAnim("hurt"),
SF.entities.push(new SF.Particle(this.x,this.y,2,this.col))):this.health+=a;"powerup"===b&&(this.counter=100,this.invincible=!0)}});
SF.Coin=SF.Sprite.extend({init:function(a){this._super(a);this.h=this.w=16;this.name="coinWave";this.checkCollision=!1;this.waveId=null;this.respawn()},update:function(){this.x+=this.vx;this.x<0-this.w&&this.respawn()},render:function(){},respawn:function(){var a,b;this._super();this.waveId=~~SF.time;SF.coins[this.waveId]=5;this.x=~~(Math.random()*SF.W)+SF.W;this.y=~~(Math.random()*(SF.H-3*this.h))+this.h;for(a=0;5>a;a+=1)b=this.x+a*this.w+8*a,SF.entities.push(new SF.CoinCollect({waveId:this.waveId,
x:b,y:this.y}));this.vx=-3;this.vy=0}});
SF.CoinCollect=SF.Sprite.extend({init:function(a){this._super(a);this.waveId=a.waveId;this.h=this.w=16;this.name="coin";this.checkCollision=!0;this.strength=0;this.vx=-3;this.sparkle=0},update:function(){this.sparkle=SF.fadeText/4;this.x+=this.vx;this.x<0-this.w&&(this.remove=!0)},render:function(){SF.Draw.circle(this.x,this.y,this.w/2,"#ffd700","brown");SF.Draw.circle(this.x,this.y,this.w/2,"rgba(255,255,255,"+this.sparkle+")")},hit:function(){var a;SF.entities.push(new SF.CoinRemove({x:this.x,y:this.y}));
SF.sfx("coin");SF.score+=10;SF.coins[this.waveId]-=1;if(0>=SF.coins[this.waveId]){SF.sfx("bonus");SF.score+=100;for(a=0;3>a;a+=1)SF.entities.push(new SF.Particle(this.x,this.y,3,"yellow","star"));SF.p1.health+=5;SF.entities.push(new SF.Text({str:"+100",col:"#c4a000",max:10,size:20,y:this.y,fade:0.01}))}this.remove=!0}});
SF.CoinRemove=SF.Sprite.extend({init:function(a){this._super(a);this.h=this.w=16;this.name="coinRemove";this.checkCollision=!1;this.vy=this.vx=-5;this.opacity=1},update:function(){this.x+=this.vx;this.y+=this.vy;this.x<0-this.w&&(this.remove=!0)},render:function(){SF.Draw.circle(this.x,this.y,this.w/2,"rgba(255,200,0,0.9)")}});
SF.Cloud=SF.Sprite.extend({init:function(a){this._super(a);this.h=this.w=16;this.name="cloud";this.checkCollision=!1;this.respawn()},update:function(){this.x+=this.vx;this.x<0-2*this.w&&this.respawn()},render:function(){SF.Draw.circle(this.x,this.y,this.w,"#fff");SF.Draw.circle(this.x+this.w,this.y,this.w,"#fff");SF.Draw.circle(this.x+this.r,this.y-this.r,this.w,"#fff")},respawn:function(){this._super();this.x=~~(Math.random()*SF.W)+SF.W;this.y=~~(Math.random()*(SF.H-3*this.h))+this.h;this.w=~~(30*
Math.random())+10;this.r=this.w/2;this.vx=(this.w-50)/5;this.vy=0}});
SF.Tree=SF.Sprite.extend({init:function(a){this._super(a);this.name="tree";this.respawn();this.checkCollision=!0},update:function(){this.x+=this.vx;this.x<0-this.w&&this.respawn()},render:function(){SF.Draw.circle(this.x+this.r,this.y+this.r-10,this.r,"green","#050");SF.Draw.circle(this.x+this.r/2,this.y+this.r-10,this.r/3,"rgba(0,0,0,0.08)");SF.Draw.rect(this.x+this.r,this.y+this.r,10,this.r,"brown","#d20")},respawn:function(){this._super();this.h=this.w=~~(64*Math.random())+32;this.r=this.w/2;this.x=
~~(Math.random()*SF.W)+SF.W;this.y=SF.H-this.h;this.vx=-3;this.vy=0}});
SF.Hornet=SF.Sprite.extend({init:function(a){a.w=16;a.h=12;a.vx=1;this._super(a);this.name="hornet";this.r=this.h/2;this.q=Math.ceil(this.r/2);this.checkCollision=!0;this.strength=-5;this.respawn()},update:function(){this.x+=this.vx;this.x<0-this.w&&this.respawn()},render:function(){var a=SF.ctx,b=this.x+this.q,c=this.y+this.q;SF.Draw.circle(b,c,this.r,"#000");SF.Draw.circle(b-5,c-2,2,"#fff");SF.Draw.circle(b+this.r,c,this.r,"#000");SF.Draw.rect(b+this.r,c-this.q+2,this.r,this.h,"yellow");a.beginPath();
a.moveTo(b+this.w,c+this.r);a.lineTo(b+this.w,c);a.lineTo(b+this.w+this.q+this.q,c+this.r);a.fillStyle="#000";a.fill();SF.Draw.circle(b+5,c-5,this.q+2,"#69a")},respawn:function(){this._super();this.x=~~(Math.random()*SF.W)+SF.W;this.y=~~(200*Math.random())+10;this.vx=-7;this.vy=0}});
SF.Fly=SF.Sprite.extend({init:function(a){a.w=22;a.h=22;a.vx=1;this._super(a);this.name="fly";this.r=this.h/2;this.q=Math.ceil(this.r/2);this.checkCollision=!0;this.respawn();this.flap=0;this.strength=-2},update:function(){this.x+=this.vx;this.x<0-this.w&&this.respawn();this.flap=SF.tick%3?3:0},render:function(){var a=SF.ctx;a.beginPath();a.moveTo(this.x+this.q,this.y+this.q);a.lineTo(this.x+this.q,this.y+this.h-3);a.lineTo(this.x-this.q,this.y+this.h/2);a.fillStyle="orange";a.strokeStyle="#c02";
a.stroke();a.fill();SF.Draw.circle(this.x+16,this.y+this.flap,6,"#666");SF.Draw.circle(this.x+this.r,this.y+this.r,this.r,"#333","#111");SF.Draw.circle(this.x+18,this.y+2+this.flap,7,"#999");SF.Draw.circle(this.x,this.y+4,4,"#fff");SF.Draw.circle(this.x-1,this.y+4,1,"#600")},respawn:function(){this._super();this.x=~~(Math.random()*SF.W)+SF.W;this.y=~~(200*Math.random())+10;this.checkCollision=!0;this.vx=-4;this.vy=0}});
SF.Snapper=SF.Sprite.extend({init:function(a){this._super(a);this.name="snapper";this.maxH=0;this.yDir=-1;this.respawn();this.strength=-5;this.checkCollision=!0},update:function(){this.x+=this.vx;if(this.y<this.maxH||this.y>SF.H)this.yDir*=-1;this.x<0-this.w&&this.respawn();this.y+=this.yDir*this.vx},render:function(){SF.Draw.rect(this.x+this.r,this.y+this.r,5,SF.H-this.y,"purple");SF.Draw.circle(this.x+this.r,this.y+this.r+this.q,this.r,"purple","#000");SF.Draw.circle(this.x+this.q,this.y+this.r+
4,this.q/2,"#fff");SF.Draw.circle(this.x+this.q+this.r,this.y+this.r+4,this.q/2,"#fff");SF.Draw.circle(this.x+this.r,this.y+this.r+2,this.q,"purple")},respawn:function(){this._super();this.h=this.w=~~(32*Math.random())+32;this.r=this.w/2;this.q=this.r/2;this.maxH=this.getMaxH();this.x=~~(Math.random()*SF.W)+SF.W;this.y=SF.H-this.h;this.vx=-3;this.vy=0},getMaxH:function(){return~~(Math.random()*(SF.H/2))+50}});
SF.Mozzie=SF.Sprite.extend({init:function(a){a.w=16;a.h=10;a.vx=1;this._super(a);this.name="mozzie";this.r=this.h/2;this.q=Math.ceil(this.r/2);this.checkCollision=!0;this.respawn();this.strength=-5;this.offScreen=!0},update:function(){this.x+=this.vx;this.x>SF.W+this.w&&this.respawn();this.offScreen=0>this.x?!0:!1},render:function(){var a=SF.ctx,b=this.x+this.q,c=this.y+this.q;this.offScreen?(SF.Draw.circle(16,c,this.h,"rgba(200,0,0,"+SF.fadeText+")"),SF.Draw.text("!",18,c+10,14,"rgba(255, 255, 255, "+
SF.fadeText+")")):(SF.Draw.circle(b,c,this.r,"#000"),SF.Draw.circle(b+this.r,c,this.r,"#000"),SF.Draw.rect(b+this.r,c-this.q+2,this.r,this.h,"black"),a.beginPath(),a.moveTo(b+this.w-3,c+this.q),a.lineTo(b+this.w,c+this.r),a.lineTo(b+this.w+this.r+this.q,c+this.r),a.fillStyle="#000",a.fill(),SF.Draw.circle(b,c-5,this.q+2,"rgba(255,255,255,0.5)"),SF.Draw.circle(this.x+this.w-2,this.y,2,"red"))},respawn:function(){this._super();this.x=-1*(~~(Math.random()*SF.W)+SF.W);this.y=~~(200*Math.random())+10;
this.vx=5;this.vy=0}});
SF.Vamp=SF.Sprite.extend({init:function(a){this._super(a);this.w=8;this.h=0;this.r=this.w/2;this.yDir=1;this.maxH=0;this.speed=3;this.name="vamp";this.respawn();this.checkCollision=!0},update:function(){this.x+=this.vx;if(this.h>this.maxH||0>this.h)this.yDir*=-1;this.x<SF.W&&(this.h+=this.yDir*this.speed);this.x<0-this.w&&this.respawn()},render:function(){SF.Draw.rect(this.x,this.y,this.w,this.h,"#c20");SF.Draw.circle(this.x-1,this.h-this.r,4,"#c20");SF.Draw.circle(this.x-2,0,12,"darkgreen");SF.Draw.circle(this.x-
this.w,4,4,"white");SF.Draw.circle(this.x+this.r,4,4,"white");SF.Draw.circle(this.x-2,0,6,"darkgreen")},respawn:function(){this._super();this.x=~~(Math.random()*SF.W)+SF.W;this.y=0;this.r=this.w/2;this.q=this.r/2;this.maxH=this.getMaxH();this.h=32;this.vx=-3;this.vy=0},getMaxH:function(){return~~(Math.random()*(SF.H/2))+50}});
SF.Powerup=SF.Sprite.extend({init:function(a){a.w=32;a.h=32;a.vx=1;this._super(a);this.name="powerup";this.r=this.h/2;this.q=Math.ceil(this.r/2);this.checkCollision=!0;this.respawn();this.strength=0},update:function(){this.x+=this.vx;this.x>SF.W+this.w&&this.respawn()},render:function(){SF.Draw.circle(this.x+this.r,this.y+this.r,this.r,"rgba(255,0,255,0.3)","#505")},respawn:function(){this._super();this.x=-1*(~~(Math.random()*SF.W)+SF.W);this.y=~~(200*Math.random())+10;this.vx=6;this.vy=0},hit:function(){var a;
SF.sfx("powerup");for(a=0;2>a;a+=1)SF.entities.push(new SF.Particle(this.x,this.y,3,"purple","star"));this.remove=!0}});SF.Button_start=SF.Button.extend({clicked:function(){SF.changeState("play");this.remove=!0}});
SF.Button_pause=SF.Button.extend({init:function(a){this._super(a);this.type="gui";this.col="rgba(255,255,255,0.8)"},clicked:function(){SF.pause||(SF.pause=!0,this.col="rgba(255,255,255,1)",SF.entities.push(new SF.Button_continue({})),SF.entities.push(new SF.Button_audio({})),SF.entities.push(new SF.Button_quit({})));SF.tapped=!1},render:function(){SF.pause?SF.Draw.rect(0,0,SF.W,SF.H,"rgba(0,0,0,0.5)"):(SF.Draw.rect(this.x+5,this.y,15,this.h,this.col),SF.Draw.rect(this.x+25,this.y,15,this.h,this.col))}});
SF.Button_tweet=SF.Button.extend({clicked:function(){alert("Tweet")}});SF.Button_splash=SF.Button.extend({clicked:function(){SF.changeState("credits");this.remove=!0}});
SF.Button_continue=SF.Button.extend({init:function(a){this._super(a);this.type="gui";this.removeOnPause=!0;this.col="green";this.x=100;this.y=140;this.img=new Image;this.img.src="a/gui.png";this.w=260;this.h=40;this.text="Continue"},clicked:function(){SF.pause=!1;this.remove=!0;var a;for(a=0;a<SF.entities.length;a+=1)SF.entities[a].removeOnPause&&(SF.entities[a].remove=!0)},render:function(){SF.Draw.roundRect(this.x,this.y,this.w,this.h,5,this.col,"#000");SF.Draw.text(this.text,!1,this.y+25,20,"#fff",
"#000");SF.ctx.drawImage(this.img,0,0,24,24,this.x+7,this.y+7,24,24)}});
SF.Button_audio=SF.Button.extend({init:function(a){this._super(a);this.type="gui";this.removeOnPause=!0;this.col="orange";this.x=100;this.y=190;this.w=260;this.h=40;this.text="Audio";this.img=new Image;this.img.src="a/gui.png"},clicked:function(){SF.hasAudio&&(SF.mute=!SF.mute,SF.tapped=!1)},render:function(){SF.hasAudio&&(SF.Draw.roundRect(this.x,this.y,this.w,this.h,5,this.col,"#000"),SF.Draw.text(this.text,!1,this.y+25,20,"#fff","#000"),SF.ctx.drawImage(this.img,24,0,24,24,this.x+7,this.y+7,24,
24),SF.mute&&SF.Draw.rect(this.x+20,this.y+this.h/3,this.w-40,5,"#c20"))}});SF.Button_more_games=SF.Button.extend({init:function(a){this._super(a);this.type="gui";this.col="#040";this.y=180;this.w=200;this.h=30;this.x=(SF.W-this.w)/2;this.text=SF.tr("more_games")},clicked:function(){SF.tapped=!1;SF.more_games_callback.call()},render:function(){SF.Draw.roundRect(this.x,this.y,this.w,this.h,5,this.col,"#000");SF.Draw.text(this.text,!1,this.y+18,14,"#fff","#000")}});
SF.Button_quit=SF.Button.extend({init:function(a){this._super(a);this.type="gui";this.removeOnPause=!0;this.col="red";this.x=100;this.y=SF.hasAudio?240:190;this.w=260;this.h=40;this.text="Quit";this.img=new Image;this.img.src="a/gui.png"},clicked:function(){var a;for(a=0;a<SF.entities.length;a+=1)SF.entities[a].removeOnPause&&(SF.entities[a].remove=!0);SF.pause=!1;this.remove=!0;SF.changeState("gameOver")},render:function(){SF.Draw.roundRect(this.x,this.y,this.w,this.h,5,this.col,"#000");SF.Draw.text(this.text,
!1,this.y+25,20,"#fff","#000");SF.ctx.drawImage(this.img,48,0,24,24,this.x+7,this.y+7,24,24)}});SF.Tap=SF.Sprite.extend({init:function(a){this._super(a);this.h=this.w=10;this.name="tap";this.checkCollision=!1;this.opacity=1;this.decay=0.05},update:function(){this.opacity-=this.decay;0>this.opacity&&(this.remove=!0)},render:function(){SF.Draw.circle(this.x,this.y,this.w/2,"rgba(200,0,0,"+this.opacity+")")}});window.addEventListener("load",SF.init,!1);SF.start_game=function(){SF.init()};
SF.more_games_callback=function(){};SF.data.phrases={en:{freebird:"Freebird",rotate_device:"Please rotate your device",more_games:"More Games",tap_to_start:"Tap to Start",click_to_start:"Click to Start",tap_to_fly:"Tap to Fly",click_to_fly:"Click to Fly",loading:"Loading",hiscore:"HiScore",game_over:"GAME OVER",score:"Score",bonus:"Bonus",paused:"Paused"},fr:{},es:{},pt:{},de:{}};
